from __future__ import annotations

from app.modes.base_mode import ModeConfig


def build_default_mode() -> ModeConfig:
    """Current project state as named default mode."""
    return ModeConfig(
        mode_id="default",
        name="Default ReID MVP",
        description=(
            "Bisheriger Stand: generische Personenerkennung, Tracking, "
            "Torchreid/OSNet-ReID, SQLite-Speicherung und Live-Preview."
        ),
        pipeline_type="person_reid",
        yolo_model="yolov8n.pt",
        tracker="bytetrack.yaml",
        encoder_backend="torchreid",
        vector_store_backend="sqlite",
        qdrant_collection="person_reid_embeddings",
        match_threshold=0.74,
        strong_match_threshold=0.82,
        weak_match_threshold=0.68,
        new_person_max_score=0.58,
        new_person_min_evidence_events=6,
        new_person_evidence_window_frames=30,
        new_person_low_match_ratio=0.80,
        pending_max_age_frames=45,
        motion_identity_bonus=0.04,
        motion_identity_max_frame_gap=15,
        motion_identity_max_distance_fraction=0.15,
        merge_candidate_threshold=0.86,
        merge_candidate_min_events=8,
        merge_candidate_same_track_required=True,
        detection_confidence=0.40,
        image_size=960,
        reid_every_n_frames=5,
        min_good_frames_before_reid=3,
        min_embedding_quality=0.60,
        min_update_quality=0.75,
        max_frames=500,
        min_crop_height=120,
        min_crop_width=45,
        crop_padding=0.08,
        calibration_detection_confidence=0.45,
        calibration_image_size=1280,
        calibration_reid_every_n_frames=3,
        calibration_min_good_frames_before_reid=5,
        calibration_min_embedding_quality=0.70,
        calibration_min_update_quality=0.80,
        calibration_min_crop_height=160,
        calibration_min_crop_width=60,
        calibration_crop_padding=0.10,
        calibration_enable_detail_analysis=False,
        device="auto",
        enable_motion_analysis=True,
        draw_motion_vectors=True,
        disable_internal_motion_when_botsort=False,
        motion_max_jump_fraction=0.20,
        motion_smoothing_alpha=0.35,
        motion_min_displacement_px=2.0,
        enable_detail_analysis=True,
        detail_weight=0.05,
        detail_min_confidence=0.70,
        draw_detail_labels=True,
    )
